const goodsList = [
  {
    id: 1,
    link: 'img/1.jpg',
    colorAmount: '4',
    title: 'Смартфон Xiaomi Redmi 6A 16 ГБ. Основная камера 13 Мп, полноэкранный дисплей.',
    price: '5768',
    catigory: 'Телефоны',
  },
  {
    id: 2,
    link: 'img/2.jpg',
    colorAmount: '3',
    title: 'Смартфон Xiaomi Redmi 6A 32 ГБ. Основная камера 13 Мп, полноэкранный дисплей, современный дизайн.',
    price: '17 600',
    catigory: 'Телефоны',
  },
  {
    id: 3,
    link: 'img/3.jpg',
    colorAmount: '2',
    title: 'Смартфон HUAWEI Y6 Prime 2018.',
    price: '6 800',
    catigory: 'Телефоны',
  },
  {
    id: 4,
    link: 'img/4.jpg',
    colorAmount: '3',
    title: 'Cмартфон Honor 7С Pro 32 ГБ. Безрамочный экран 5, 99".',
    price: '7 200',
    catigory: 'Телефоны',
  },
  {
    id: 5,
    link: 'img/5.jpg',
    colorAmount: '2',
    title: 'Смартфон Xiaomi Redmi 5 16 ГБ с широким экраном.',
    price: '9 630',
    catigory: 'Телефоны',
  },
  {
    id: 6,
    link: 'img/6.jpg',
    colorAmount: '4',
    title: 'Cмартфон Honor 8X 64 ГБ. Безрамочный экран FullView 6,5“. Доставка из России от 2 дней.',
    price: '15 990',
    catigory: 'Телефоны',
  },
  {
    id: 7,
    link: 'img/7.jpg',
    colorAmount: '5',
    title: 'Смартфон HUAWEI P20 lite',
    price: '13 990',
    catigory: 'Телефоны',
  },
  {
    id: 8,
    link: 'img/8.jpg',
    colorAmount: '3',
    title: 'Смартфон Xiaomi Mi8 Lite 4 + 64 ГБ',
    price: '17 990',
    catigory: 'Телефоны',
  }
]
